# Generated by Django 5.2.7 on 2025-10-26 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='poc',
            name='title',
            field=models.CharField(default='no title', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='nothing', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('user',)},
        ),
    ]
