# Generated by Django 5.2.7 on 2025-10-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_poc_title_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='profile_pictures/default.png', upload_to='profile_pictures'),
        ),
    ]
